name: flutter_elinux
description: Flutter application build tools for Embedded Linux devices
homepage: https://github.com/sony/flutter-elinux
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_tools:
    path: flutter/packages/flutter_tools
  file: # inherit from flutter_tools
  meta:
  package_config:
  path:
  process:
  xml:
  yaml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
